



/*
5.	Write a C program to print Fibonacci Sequence up to a certain number input by you.
Hint: Fibonacci series is a series of numbers formed by the addition of the preceding two numbers in the series.
The first two terms are zero and one respectively. The terms after this are generated by simply adding the previous two terms.
*/
#include <stdio.h>
int main()
{
    int term1 = 0, term2 = 1 , term3 = term1+term2, input;
    scanf("%d" , &input);
    printf("\n%d\n%d" , term1 , term2);
    while(term3 <= input)
    {
        printf("\n%d" , term3);
        term1 = term2;
        term2 = term3;
        term3 = term1 + term2;
    }

}